apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ai-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: YOUR_DOCKERHUB/frontend:latest

          ports:
            - containerPort: 8000

          env:
            - name: BOOTSTRAP_SERVER
              value: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092

            - name: PRODUCING_TOPIC
              value: image_upload

            - name: CONSUMING_TOPIC
              value: classification_result

            - name: MYSQL_HOST
              value: mysql-service

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password

            - name: MYSQL_DATABASE
              value: image_db

            - name: MYSQL_TABLE
              value: image_audit

            - name: S3_BUCKET
              value: my-imageclass

            - name: S3_FOLDER
              value: datasets

            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: access-key

            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: secret-key

            - name: AWS_REGION
              value: us-east-1
          resources:
            requests:
              cpu: 200m
              memory: 256Mi

            limits:
              cpu: 500m
              memory: 512Mi

          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15

          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20