apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: ai-pipeline
type: Opaque
stringData:
  mongo-uri: mongodb://resultsDumper:resultsDumper%269099@mongodb-service:27017/detection_results?authSource=detection_results