# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detector.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'detector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x65tector.proto\"\x1d\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"c\n\tDetection\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\n\n\x02x1\x18\x03 \x01(\x05\x12\n\n\x02y1\x18\x04 \x01(\x05\x12\n\n\x02x2\x18\x05 \x01(\x05\x12\n\n\x02y2\x18\x06 \x01(\x05\"3\n\x11\x44\x65tectionResponse\x12\x1e\n\ndetections\x18\x01 \x03(\x0b\x32\n.Detection2>\n\x08\x44\x65tector\x12\x32\n\rDetectObjects\x12\r.ImageRequest\x1a\x12.DetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=18
  _globals['_IMAGEREQUEST']._serialized_end=47
  _globals['_DETECTION']._serialized_start=49
  _globals['_DETECTION']._serialized_end=148
  _globals['_DETECTIONRESPONSE']._serialized_start=150
  _globals['_DETECTIONRESPONSE']._serialized_end=201
  _globals['_DETECTOR']._serialized_start=203
  _globals['_DETECTOR']._serialized_end=265
# @@protoc_insertion_point(module_scope)
